name: Build module

on: 
  pull_request:
    paths:
      - 'src/**'
      - 'moduleinfo.json'
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Build
        shell: pwsh
        run: |
          & .\build.ps1
      
      - name: upload artifacts
        uses: actions/upload-artifact@v7
        with:
          name: Module
          path: ./CheckMK/
          if-no-files-found: error
